# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Linux application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install pygubu
        pip install tk
        pip install -U pyinstaller
    - name: Make exe
      run: |
        pyinstaller --onefile app.py
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: /home/runner/work/LottoChecker-GUI/LottoChecker-GUI/build/app/app
    - name: Release
      uses: fnkr/github-action-ghr@v1
      env:
        GHR_PATH: /home/runner/work/LottoChecker-GUI/LottoChecker-GUI/build/app/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
